<?php

$products = [
    0 => [
        "id" => 1,
        "name" => "Asus Rog Strix G15",
        "brand" => "Asus",
        "category" => "Laptop", 
        "title" => "Laptop Asus Rog Strix G15 Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "asus-rog-strix-g15"
    ],
    1 => [
        "id" => 2,
        "name" => "Acer Aspire 7",
        "brand" => "Aser",
        "category" => "Smartphone", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-7"
    ],
    2 => [
        "id" => 3,
        "name" => "Acer Aspire 1",
        "brand" => "Aser",
        "category" => "Tablet", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-1"
    ],
    3 => [
        "id" => 4,
        "name" => "Acer Aspire 2",
        "brand" => "Aser",
        "category" => "Laptop", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-2"
    ],
    4 => [
        "id" => 5,
        "name" => "Acer Aspire 3",
        "brand" => "Aser",
        "category" => "Smartphone", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-3"
    ],
    5 => [
        "id" => 6,
        "name" => "Acer Aspire 4",
        "brand" => "Aser",
        "category" => "Tablet", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-4"
    ],
    6 => [
        "id" => 7,
        "name" => "Acer Aspire 5",
        "brand" => "Aser",
        "category" => "Laptop", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-5"
    ],
    7 => [
        "id" => 8,
        "name" => "Acer Aspire 6",
        "brand" => "Aser",
        "category" => "Smartphone", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-6"
    ],
    8 => [
        "id" => 9,
        "name" => "Acer Aspire 8",
        "brand" => "Aser",
        "category" => "Tablet", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-8"
    ],
    9 => [
        "id" => 10,
        "name" => "Acer Aspire 9",
        "brand" => "Aser",
        "category" => "Laptop", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-8"
    ],
    10 => [
        "id" => 11,
        "name" => "Acer Aspire 10",
        "brand" => "Aser",
        "category" => "Tablet", 
        "title" => "Laptop Acer Aspire 7 Charcoal Black",
        "image" => "/assets/images/laptop.jpg",
        "price" => 450.00,
        "desc" => "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed aliquam architecto qui recusandae dolorem exercitationem, in quasi vitae illum perspiciatis tempora, omnis repellat odio, quas repudiandae? Animi numquam consectetur beatae.
                    Aperiam, sit consequuntur animi, harum esse inventore laudantium et laboriosam mollitia facere, fugiat ad dolores id modi error assumenda! Amet labore ut doloremque possimus asperiores facere eveniet sit, sed et?
                    Nesciunt esse vero culpa velit veritatis quo tempore ut voluptas, et, incidunt perferendis quasi nostrum cumque? Neque non vero laudantium, sunt fugiat ducimus libero, maxime vel nostrum tempore, fugit corrupti.
                    Vel similique eligendi illo sint doloremque adipisci dolores quasi consectetur excepturi natus ut deleniti qui, nihil in repellat impedit veniam ducimus sapiente! Fugiat, exercitationem. Quaerat repellat totam vero impedit quasi!",
        "screen" => "15.6 IPS (1920x1080) Full HD",
        "cpu" => "Intel Core i5-10500H (2.5 - 4.5)",
        "ram" => "16Gb",
        "ssd" => "512Gb",
        "hdd" => "1Tb",
        "graphics_card" => "nVidia GeForce RTX 1060 4Gb",
        "color" => "black",
        "cores" => 4,
        "chipset" => "intel z280",
        "type_of_ram" => "ddr4",
        "system" => "Free DOS",
        "hdmi" => "yes",
        "wifi" => "yes",
        "country" => "china",
        "alias" => "acer-aspire-10"
    ],
];

return $products;